import { City } from "../models/city";

const cities: City[] = [
  {
    name: "Barcelona",
    location: {
      latitude: 41.3851,
      longitude: 2.1734,
    },
    image:
      "https://images.unsplash.com/photo-1474351622873-3a37a2545060?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A001",
        name: "Sagrada Familia",
        city: "Barcelona",
        location: { latitude: 41.4035, longitude: 2.1743 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A002",
        name: "Park Güell",
        city: "Barcelona",
        location: { latitude: 41.4143, longitude: 2.1526 },
        estimatedTime: 120,
        perPersonCost: 10,
      },
      {
        id: "A003",
        name: "La Rambla",
        city: "Barcelona",
        location: { latitude: 41.3842, longitude: 2.1709 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A004",
        name: "Casa Batlló",
        city: "Barcelona",
        location: { latitude: 41.3918, longitude: 2.1652 },
        estimatedTime: 120,
        perPersonCost: 25,
      },
      {
        id: "A005",
        name: "La Barceloneta",
        city: "Barcelona",
        location: { latitude: 41.3779, longitude: 2.1922 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A006",
        name: "Montjuïc",
        city: "Barcelona",
        location: { latitude: 41.367, longitude: 2.1685 },
        estimatedTime: 240,
        perPersonCost: 0,
      },
      {
        id: "A007",
        name: "Magic Fountain of Montjuïc",
        city: "Barcelona",
        location: { latitude: 41.3713, longitude: 2.1516 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A008",
        name: "Casa Milà (La Pedrera)",
        city: "Barcelona",
        location: { latitude: 41.3954, longitude: 2.1619 },
        estimatedTime: 120,
        perPersonCost: 25,
      },
      {
        id: "A009",
        name: "Camp Nou",
        city: "Barcelona",
        location: { latitude: 41.381, longitude: 2.1227 },
        estimatedTime: 180,
        perPersonCost: 25,
      },

      {
        id: "A010",
        name: "Barcelona Aquarium",
        city: "Barcelona",
        location: { latitude: 41.377, longitude: 2.1843 },
        estimatedTime: 90,
        perPersonCost: 20,
      },

      {
        id: "A011",
        name: "Picasso Museum",
        city: "Barcelona",
        location: { latitude: 41.3854, longitude: 2.1809 },
        estimatedTime: 120,
        perPersonCost: 15,
      },

      {
        id: "A012",
        name: "Tibidabo Amusement Park",
        city: "Barcelona",
        location: { latitude: 41.4224, longitude: 2.1191 },
        estimatedTime: 180,
        perPersonCost: 30,
      },

      {
        id: "A013",
        name: "Barcelona Cathedral",
        city: "Barcelona",
        location: { latitude: 41.3841, longitude: 2.1762 },
        estimatedTime: 90,
        perPersonCost: 0,
      },

      {
        id: "A014",
        name: "Palau de la Música Catalana",
        city: "Barcelona",
        location: { latitude: 41.3877, longitude: 2.1753 },
        estimatedTime: 90,
        perPersonCost: 20,
      },

      {
        id: "A015",
        name: "Parc de la Ciutadella",
        city: "Barcelona",
        location: { latitude: 41.3882, longitude: 2.1859 },
        estimatedTime: 150,
        perPersonCost: 0,
      },

      {
        id: "A016",
        name: "Museu Nacional d'Art de Catalunya (MNAC)",
        city: "Barcelona",
        location: { latitude: 41.3686, longitude: 2.1536 },
        estimatedTime: 120,
        perPersonCost: 20,
      },

      {
        id: "A017",
        name: "Plaça de Catalunya",
        city: "Barcelona",
        location: { latitude: 41.387, longitude: 2.17 },
        estimatedTime: 60,
        perPersonCost: 0,
      },

      {
        id: "A018",
        name: "Poble Espanyol",
        city: "Barcelona",
        location: { latitude: 41.3689, longitude: 2.1482 },
        estimatedTime: 90,
        perPersonCost: 20,
      },

      {
        id: "A019",
        name: "Hospital de Sant Pau",
        city: "Barcelona",
        location: { latitude: 41.4135, longitude: 2.1793 },
        estimatedTime: 90,
        perPersonCost: 0,
      },

      {
        id: "A020",
        name: "CosmoCaixa Barcelona",
        city: "Barcelona",
        location: { latitude: 41.4132, longitude: 2.1308 },
        estimatedTime: 120,
        perPersonCost: 10,
      },

      {
        id: "A021",
        name: "Joan Miró Foundation",
        city: "Barcelona",
        location: { latitude: 41.3688, longitude: 2.1597 },
        estimatedTime: 90,
        perPersonCost: 15,
      },

      {
        id: "A022",
        name: "Mercat de la Boqueria",
        city: "Barcelona",
        location: { latitude: 41.3819, longitude: 2.1716 },
        estimatedTime: 60,
        perPersonCost: 0,
      },

      {
        id: "A023",
        name: "Casa de les Punxes",
        city: "Barcelona",
        location: { latitude: 41.3982, longitude: 2.164 },
        estimatedTime: 90,
        perPersonCost: 20,
      },

      {
        id: "A024",
        name: "Casa Vicens",
        city: "Barcelona",
        location: { latitude: 41.4036, longitude: 2.1506 },
        estimatedTime: 90,
        perPersonCost: 20,
      },

      {
        id: "A025",
        name: "Basilica of Santa Maria del Mar",
        city: "Barcelona",
        location: { latitude: 41.384, longitude: 2.182 },
        estimatedTime: 90,
        perPersonCost: 0,
      },

      {
        id: "A026",
        name: "Maremagnum",
        city: "Barcelona",
        location: { latitude: 41.3748, longitude: 2.1823 },
        estimatedTime: 60,
        perPersonCost: 0,
      },

      {
        id: "A027",
        name: "Barcelona Zoo",
        city: "Barcelona",
        location: { latitude: 41.38639433144287, longitude: 2.1871 },
        estimatedTime: 120,
        perPersonCost: 20,
      },

      {
        id: "A028",
        name: "CaixaForum Barcelona",
        city: "Barcelona",
        location: { latitude: 41.3714, longitude: 2.1495 },
        estimatedTime: 90,
        perPersonCost: 0,
      },

      {
        id: "A029",
        name: "Plaça Reial",
        city: "Barcelona",
        location: { latitude: 41.3801, longitude: 2.1753 },
        estimatedTime: 60,
        perPersonCost: 0,
      },

      {
        id: "A030",
        name: "Torre Agbar",
        city: "Barcelona",
        location: { latitude: 41.4036, longitude: 2.1895 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
    ],
  },
  {
    name: "London",
    location: {
      latitude: 51.5074,
      longitude: -0.118,
    },
    image:
      "https://images.unsplash.com/photo-1486299267070-83823f5448dd?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A031",
        name: "Tower of London",
        city: "London",
        location: { latitude: 51.5082, longitude: -0.0759 },
        estimatedTime: 180,
        perPersonCost: 30,
      },
      {
        id: "A032",
        name: "British Museum",
        city: "London",
        location: { latitude: 51.5195, longitude: -0.127 },
        estimatedTime: 240,
        perPersonCost: 20,
      },
      {
        id: "A033",
        name: "Buckingham Palace",
        city: "London",
        location: { latitude: 51.5015, longitude: -0.1416 },
        estimatedTime: 120,
        perPersonCost: 10,
      },
      {
        id: "A034",
        name: "Big Ben and the Houses of Parliament",
        city: "London",
        location: { latitude: 51.5008, longitude: -0.1246 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A035",
        name: "The British Library",
        city: "London",
        location: { latitude: 51.5302, longitude: -0.1277 },
        estimatedTime: 90,
        perPersonCost: 10,
      },
      {
        id: "A036",
        name: "Tate Modern",
        city: "London",
        location: { latitude: 51.5076, longitude: -0.0993 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A037",
        name: "The Shard",
        city: "London",
        location: { latitude: 51.5046, longitude: -0.0865 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A038",
        name: "Hyde Park",
        city: "London",
        location: { latitude: 51.5075, longitude: -0.1641 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A039",
        name: "Westminster Abbey",
        city: "London",
        location: { latitude: 51.4995, longitude: -0.1273 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A040",
        name: "The Natural History Museum",
        city: "London",
        location: { latitude: 51.4968, longitude: -0.1764 },
        estimatedTime: 120,
        perPersonCost: 30,
      },
      {
        id: "A041",
        name: "The Victoria and Albert Museum",
        city: "London",
        location: { latitude: 51.4968, longitude: -0.1721 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A042",
        name: "St. Paul's Cathedral",
        city: "London",
        location: { latitude: 51.514, longitude: -0.0983 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A043",
        name: "The Globe Theatre",
        city: "London",
        location: { latitude: 51.5069, longitude: -0.0947 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A044",
        name: "Tower Bridge",
        city: "London",
        location: { latitude: 51.5055, longitude: -0.0753 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A045",
        name: "Camden Market",
        city: "London",
        location: { latitude: 51.5416, longitude: -0.1464 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A046",
        name: "Covent Garden",
        city: "London",
        location: { latitude: 51.5268, longitude: -0.1343 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A047",
        name: "The Tate Britain",
        city: "London",
        location: { latitude: 51.4911, longitude: -0.1278 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A048",
        name: "Kensington Palace",
        city: "London",
        location: { latitude: 51.5051, longitude: -0.1876 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A049",
        name: "The Serpentine Gallery",
        city: "London",
        location: { latitude: 51.5048, longitude: -0.1751 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A050",
        name: "HMS Belfast",
        city: "London",
        location: { latitude: 51.5067, longitude: -0.0814 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A051",
        name: "The Royal Observatory Greenwich",
        city: "London",
        location: { latitude: 51.4769, longitude: -0.0004 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A052",
        name: "The London Eye",
        city: "London",
        location: { latitude: 51.5033, longitude: -0.1195 },
        estimatedTime: 60,
        perPersonCost: 30,
      },
      {
        id: "A053",
        name: "The Science Museum",
        city: "London",
        location: { latitude: 51.4973, longitude: -0.1764 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A054",
        name: "The National Maritime Museum",
        city: "London",
        location: { latitude: 51.4811, longitude: -0.0052 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A055",
        name: "The O2",
        city: "London",
        location: { latitude: 51.5033, longitude: 0.0033 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A056",
        name: "The National Portrait Gallery",
        city: "London",
        location: { latitude: 51.5095, longitude: -0.1277 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A057",
        name: "The Royal Albert Hall",
        city: "London",
        location: { latitude: 51.501, longitude: -0.1773 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A058",
        name: "The Victoria Embankment Gardens",
        city: "London",
        location: { latitude: 51.5081, longitude: -0.1225 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A059",
        name: "The Cutty Sark",
        city: "London",
        location: { latitude: 51.4829, longitude: -0.0096 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A060",
        name: "Leadenhall Market",
        city: "London",
        location: { latitude: 51.5129, longitude: -0.0834 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
    ],
  },
  {
    name: "Vienna",
    location: {
      latitude: 48.2082,
      longitude: 16.3738,
    },
    image:
      "https://images.unsplash.com/photo-1573599852326-2d4da0bbe613?q=80&w=1990&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A061",
        name: "Schönbrunn Palace",
        city: "Vienna",
        location: { latitude: 48.1859, longitude: 16.3127 },
        estimatedTime: 180,
        perPersonCost: 20,
      },
      {
        id: "A062",
        name: "St. Stephen's Cathedral",
        city: "Vienna",
        location: { latitude: 48.2085, longitude: 16.3736 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A063",
        name: "Belvedere Palace",
        city: "Vienna",
        location: { latitude: 48.1916, longitude: 16.3808 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A064",
        name: "Vienna State Opera",
        city: "Vienna",
        location: { latitude: 48.2036, longitude: 16.3691 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A065",
        name: "Hofburg Palace",
        city: "Vienna",
        location: { latitude: 48.2057, longitude: 16.3647 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A066",
        name: "Prater Park",
        city: "Vienna",
        location: { latitude: 48.2157, longitude: 16.4001 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A067",
        name: "Kunsthistorisches Museum",
        city: "Vienna",
        location: { latitude: 48.2039, longitude: 16.3617 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A068",
        name: "Naschmarkt",
        city: "Vienna",
        location: { latitude: 48.1987, longitude: 16.3636 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A069",
        name: "Albertina Museum",
        city: "Vienna",
        location: { latitude: 48.2048, longitude: 16.3681 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A070",
        name: "Vienna City Hall",
        city: "Vienna",
        location: { latitude: 48.211, longitude: 16.3564 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A071",
        name: "The Hofburg Congress Center",
        city: "Vienna",
        location: { latitude: 48.2062, longitude: 16.3653 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A072",
        name: "Kaisergruft",
        city: "Vienna",
        location: { latitude: 48.2058, longitude: 16.3701 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A073",
        name: "Leopold Museum",
        city: "Vienna",
        location: { latitude: 48.2027, longitude: 16.3592 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A074",
        name: "Schönbrunn Zoo",
        city: "Vienna",
        location: { latitude: 48.1822, longitude: 16.3027 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A075",
        name: "Vienna Secession Building",
        city: "Vienna",
        location: { latitude: 48.2004, longitude: 16.3659 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A076",
        name: "Hundertwasserhaus",
        city: "Vienna",
        location: { latitude: 48.2074, longitude: 16.3943 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A077",
        name: "Graben",
        city: "Vienna",
        location: { latitude: 48.2087, longitude: 16.3695 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A078",
        name: "Museum of Natural History",
        city: "Vienna",
        location: { latitude: 48.2053, longitude: 16.3601 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A079",
        name: "Vienna Woods",
        city: "Vienna",
        location: { latitude: 48.1116, longitude: 15.9527 },
        estimatedTime: 380,
        perPersonCost: 0,
      },
      {
        id: "A080",
        name: "Kahlenberg",
        city: "Vienna",
        location: { latitude: 48.278, longitude: 16.3339 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A081",
        name: "The State Hall of the Austrian National Library",
        city: "Vienna",
        location: { latitude: 48.2064, longitude: 16.367 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A082",
        name: "Vienna City Museum",
        city: "Vienna",
        location: { latitude: 48.1995, longitude: 16.3729 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A083",
        name: "MuseumQuartier",
        city: "Vienna",
        location: { latitude: 48.2033, longitude: 16.3585 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A084",
        name: "Spanish Riding School",
        city: "Vienna",
        location: { latitude: 48.2079, longitude: 16.3661 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A085",
        name: "House of Music",
        city: "Vienna",
        location: { latitude: 48.204, longitude: 16.373 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A086",
        name: "Augarten",
        city: "Vienna",
        location: { latitude: 48.2276, longitude: 16.3761 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A087",
        name: "Funeral Museum",
        city: "Vienna",
        location: { latitude: 48.151, longitude: 16.4402 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A088",
        name: "Lainzer Tiergarten",
        city: "Vienna",
        location: { latitude: 48.1696, longitude: 16.2205 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A089",
        name: "Donauturm",
        city: "Vienna",
        location: { latitude: 48.2404, longitude: 16.41 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A090",
        name: "Museum of Military History",
        city: "Vienna",
        location: { latitude: 48.1844, longitude: 16.3889 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
    ],
  },
  {
    name: "Paris",
    location: {
      latitude: 48.8566,
      longitude: 2.3522,
    },
    image:
      "https://images.unsplash.com/photo-1431274172761-fca41d930114?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A091",
        name: "Eiffel Tower",
        city: "Paris",
        location: { latitude: 48.8584, longitude: 2.2944 },
        estimatedTime: 100,
        perPersonCost: 20,
      },
      {
        id: "A092",
        name: "Louvre Museum",
        city: "Paris",
        location: { latitude: 48.8606, longitude: 2.3376 },
        estimatedTime: 180,
        perPersonCost: 20,
      },
      {
        id: "A093",
        name: "Notre-Dame Cathedral",
        city: "Paris",
        location: { latitude: 48.853, longitude: 2.3499 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A094",
        name: "Montmartre",
        city: "Paris",
        location: { latitude: 48.886, longitude: 2.343 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A095",
        name: "Musée d'Orsay",
        city: "Paris",
        location: { latitude: 48.8599, longitude: 2.3266 },
        estimatedTime: 180,
        perPersonCost: 20,
      },
      {
        id: "A096",
        name: "Seine River Cruise",
        city: "Paris",
        location: { latitude: 48.8588, longitude: 2.295 },
        estimatedTime: 180,
        perPersonCost: 20,
      },
      {
        id: "A097",
        name: "Sainte-Chapelle",
        city: "Paris",
        location: { latitude: 48.8555, longitude: 2.3453 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A098",
        name: "Musée de l'Orangerie",
        city: "Paris",
        location: { latitude: 48.8635, longitude: 2.3224 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A099",
        name: "Champs-Élysées and Arc de Triomphe",
        city: "Paris",
        location: { latitude: 48.8738, longitude: 2.295 },
        estimatedTime: 180,
        perPersonCost: 0,
      },
      {
        id: "A100",
        name: "Panthéon",
        city: "Paris",
        location: { latitude: 48.8462, longitude: 2.3465 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A101",
        name: "Centre Pompidou",
        city: "Paris",
        location: { latitude: 48.8606, longitude: 2.3522 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A102",
        name: "Musée Rodin",
        city: "Paris",
        location: { latitude: 48.8554, longitude: 2.3159 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A103",
        name: "Luxembourg Gardens",
        city: "Paris",
        location: { latitude: 48.8462, longitude: 2.3374 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A104",
        name: "Les Invalides",
        city: "Paris",
        location: { latitude: 48.8587, longitude: 2.3144 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A105",
        name: "Palais Garnier - Opéra National de Paris",
        city: "Paris",
        location: { latitude: 48.8718, longitude: 2.3311 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A106",
        name: "Musée Picasso Paris",
        city: "Paris",
        location: { latitude: 48.8599, longitude: 2.3624 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A107",
        name: "Saint-Germain-des-Prés",
        city: "Paris",
        location: { latitude: 48.853, longitude: 2.3338 },
        estimatedTime: 180,
        perPersonCost: 0,
      },
      {
        id: "A108",
        name: "Moulin Rouge",
        city: "Paris",
        location: { latitude: 48.8843, longitude: 2.3323 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A109",
        name: "Cité des Sciences et de l'Industrie",
        city: "Paris",
        location: { latitude: 48.8956, longitude: 2.386 },
        estimatedTime: 180,
        perPersonCost: 20,
      },
      {
        id: "A110",
        name: "Musée de l'Armée",
        city: "Paris",
        location: { latitude: 48.8558, longitude: 2.3131 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A111",
        name: "Pont Alexandre III",
        city: "Paris",
        location: { latitude: 48.8638, longitude: 2.313 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A112",
        name: "Île de la Cité",
        city: "Paris",
        location: { latitude: 48.8549, longitude: 2.3488 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A113",
        name: "Musée Carnavalet",
        city: "Paris",
        location: { latitude: 48.857, longitude: 2.362 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A114",
        name: "Parc des Buttes-Chaumont",
        city: "Paris",
        location: { latitude: 48.8809, longitude: 2.3827 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A115",
        name: "Place des Vosges",
        city: "Paris",
        location: { latitude: 48.8554, longitude: 2.3655 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A116",
        name: "Père Lachaise Cemetery",
        city: "Paris",
        location: { latitude: 48.861, longitude: 2.3934 },
        estimatedTime: 180,
        perPersonCost: 0,
      },
      {
        id: "A117",
        name: "Canal Saint-Martin",
        city: "Paris",
        location: { latitude: 48.8688, longitude: 2.3671 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A118",
        name: "Basilique du Sacré-Cœur",
        city: "Paris",
        location: { latitude: 48.8867, longitude: 2.3431 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A119",
        name: "Palais Royal",
        city: "Paris",
        location: { latitude: 48.8634, longitude: 2.337 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A120",
        name: "La Défense",
        city: "Paris",
        location: { latitude: 48.8886, longitude: 2.2418 },
        estimatedTime: 220,
        perPersonCost: 0,
      },
    ],
  },
  {
    name: "New York",
    location: {
      latitude: 40.7128,
      longitude: -74.006,
    },
    image:
      "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?q=80&w=2099&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A121",
        name: "Statue of Liberty",
        city: "New York",
        location: { latitude: 40.6892, longitude: -74.0445 },
        estimatedTime: 280,
        perPersonCost: 20,
      },
      {
        id: "A122",
        name: "Central Park",
        city: "New York",
        location: { latitude: 40.7851, longitude: -73.9683 },
        estimatedTime: 280,
        perPersonCost: 0,
      },
      {
        id: "A123",
        name: "Times Square",
        city: "New York",
        location: { latitude: 40.7589, longitude: -73.9851 },
        estimatedTime: 220,
        perPersonCost: 0,
      },
      {
        id: "A124",
        name: "Empire State Building",
        city: "New York",
        location: { latitude: 40.7484, longitude: -73.9857 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A125",
        name: "The Metropolitan Museum of Art",
        city: "New York",
        location: { latitude: 40.7794, longitude: -73.9632 },
        estimatedTime: 180,
        perPersonCost: 20,
      },
      {
        id: "A126",
        name: "Brooklyn Bridge",
        city: "New York",
        location: { latitude: 40.7061, longitude: -73.9969 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A127",
        name: "One World Observatory",
        city: "New York",
        location: { latitude: 40.7127, longitude: -74.0134 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A128",
        name: "The High Line",
        city: "New York",
        location: { latitude: 40.7479, longitude: -74.0048 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A129",
        name: "Rockefeller Center",
        city: "New York",
        location: { latitude: 40.7587, longitude: -73.9787 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A130",
        name: "Museum of Modern Art (MoMA)",
        city: "New York",
        location: { latitude: 40.7614, longitude: -73.9776 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A131",
        name: "Grand Central Terminal",
        city: "New York",
        location: { latitude: 40.7527, longitude: -73.9772 },
        estimatedTime: 140,
        perPersonCost: 0,
      },
      {
        id: "A132",
        name: "The Solomon R. Guggenheim Museum",
        city: "New York",
        location: { latitude: 40.7829, longitude: -73.958 },
        estimatedTime: 140,
        perPersonCost: 30,
      },
      {
        id: "A133",
        name: "Battery Park",
        city: "New York",
        location: { latitude: 40.7033, longitude: -74.017 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A134",
        name: "Coney Island",
        city: "New York",
        location: { latitude: 40.5755, longitude: -73.9707 },
        estimatedTime: 220,
        perPersonCost: 0,
      },
      {
        id: "A135",
        name: "The Bronx Zoo",
        city: "New York",
        location: { latitude: 40.8506, longitude: -73.8785 },
        estimatedTime: 220,
        perPersonCost: 20,
      },
      {
        id: "A136",
        name: "The Cloisters",
        city: "New York",
        location: { latitude: 40.8645, longitude: -73.9312 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A137",
        name: "Vessel (structure)",
        city: "New York",
        location: { latitude: 40.7536, longitude: -74.0029 },
        estimatedTime: 100,
        perPersonCost: 0,
      },
      {
        id: "A138",
        name: "The Intrepid Sea, Air & Space Museum",
        city: "New York",
        location: { latitude: 40.7646, longitude: -73.9991 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A139",
        name: "St. Patrick's Cathedral",
        city: "New York",
        location: { latitude: 40.7587, longitude: -73.9764 },
        estimatedTime: 100,
        perPersonCost: 0,
      },
      {
        id: "A140",
        name: "Washington Square Park",
        city: "New York",
        location: { latitude: 40.7308, longitude: -73.9973 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A141",
        name: "The Frick Collection",
        city: "New York",
        location: { latitude: 40.7711, longitude: -73.9672 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A142",
        name: "Chelsea Market",
        city: "New York",
        location: { latitude: 40.7424, longitude: -74.006 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A143",
        name: "Top of the Rock Observation Deck",
        city: "New York",
        location: { latitude: 40.7593, longitude: -73.9794 },
        estimatedTime: 100,
        perPersonCost: 20,
      },
      {
        id: "A144",
        name: "American Museum of Natural History",
        city: "New York",
        location: { latitude: 40.7813, longitude: -73.9734 },
        estimatedTime: 160,
        perPersonCost: 20,
      },
      {
        id: "A145",
        name: "The Morgan Library & Museum",
        city: "New York",
        location: { latitude: 40.7493, longitude: -73.9817 },
        estimatedTime: 100,
        perPersonCost: 20,
      },
      {
        id: "A146",
        name: "Madison Square Garden",
        city: "New York",
        location: { latitude: 40.7505, longitude: -73.9934 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A147",
        name: "The New York Botanical Garden",
        city: "New York",
        location: { latitude: 40.8626, longitude: -73.8773 },
        estimatedTime: 220,
        perPersonCost: 10,
      },
      {
        id: "A148",
        name: "The Museum of the City of New York",
        city: "New York",
        location: { latitude: 40.7926, longitude: -73.9514 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A149",
        name: "The National September 11 Memorial & Museum",
        city: "New York",
        location: { latitude: 40.7115, longitude: -74.0134 },
        estimatedTime: 220,
        perPersonCost: 20,
      },
      {
        id: "A150",
        name: "The Whitney Museum of American Art",
        city: "New York",
        location: { latitude: 40.7395, longitude: -74.0089 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
    ],
  },
  {
    name: "Rome",
    location: {
      latitude: 41.9028,
      longitude: 12.4964,
    },
    image:
      "https://images.unsplash.com/photo-1588614959060-4d144f28b207?q=80&w=1986&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A151",
        name: "Colosseum",
        city: "Rome",
        location: { latitude: 41.8902, longitude: 12.4924 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A152",
        name: "Roman Forum",
        city: "Rome",
        location: { latitude: 41.8925, longitude: 12.4864 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A153",
        name: "Pantheon",
        city: "Rome",
        location: { latitude: 41.8986, longitude: 12.4768 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A154",
        name: "Trevi Fountain",
        city: "Rome",
        location: { latitude: 41.9009, longitude: 12.4832 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A155",
        name: "Vatican City",
        city: "Rome",
        location: { latitude: 41.9022, longitude: 12.4572 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A156",
        name: "St. Peter's Basilica",
        city: "Rome",
        location: { latitude: 41.9022, longitude: 12.4539 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A157",
        name: "Sistine Chapel",
        city: "Rome",
        location: { latitude: 41.9029, longitude: 12.4541 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A158",
        name: "Spanish Steps",
        city: "Rome",
        location: { latitude: 41.9051, longitude: 12.4828 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A159",
        name: "Navona Square",
        city: "Rome",
        location: { latitude: 41.8992, longitude: 12.4733 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A160",
        name: "Castel Sant'Angelo",
        city: "Rome",
        location: { latitude: 41.9029, longitude: 12.4663 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A161",
        name: "Trastevere",
        city: "Rome",
        location: { latitude: 41.8898, longitude: 12.4674 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A162",
        name: "Capitoline Museums",
        city: "Rome",
        location: { latitude: 41.8923, longitude: 12.4821 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A163",
        name: "Villa Borghese Gardens",
        city: "Rome",
        location: { latitude: 41.9123, longitude: 12.4851 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A164",
        name: "Venezia Square",
        city: "Rome",
        location: { latitude: 41.9016, longitude: 12.4828 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A165",
        name: "Baths of Caracalla",
        city: "Rome",
        location: { latitude: 41.8782, longitude: 12.4924 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A166",
        name: "Altare della Patria",
        city: "Rome",
        location: { latitude: 41.8947, longitude: 12.4833 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A167",
        name: "Campo de' Fiori",
        city: "Rome",
        location: { latitude: 41.8956, longitude: 12.4724 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A168",
        name: "Aventine Hill",
        city: "Rome",
        location: { latitude: 41.8839, longitude: 12.4776 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A169",
        name: "Palatine Hill",
        city: "Rome",
        location: { latitude: 41.8895, longitude: 12.4883 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A170",
        name: "Mouth of Truth",
        city: "Rome",
        location: { latitude: 41.8882, longitude: 12.4815 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A171",
        name: "Piazza del Popolo",
        city: "Rome",
        location: { latitude: 41.9109, longitude: 12.4764 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A172",
        name: "Palazzo Venezia",
        city: "Rome",
        location: { latitude: 41.8962, longitude: 12.4819 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A173",
        name: "Piazza di Spagna",
        city: "Rome",
        location: { latitude: 41.9057, longitude: 12.4829 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A174",
        name: "Quirinal Palace",
        city: "Rome",
        location: { latitude: 41.9022, longitude: 12.4867 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A175",
        name: "Basilica di Santa Maria Maggiore",
        city: "Rome",
        location: { latitude: 41.8976, longitude: 12.4982 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A176",
        name: "Borghese Gallery",
        city: "Rome",
        location: { latitude: 41.9145, longitude: 12.4924 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A177",
        name: "Circus Maximus",
        city: "Rome",
        location: { latitude: 41.8886, longitude: 12.4871 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A178",
        name: "Janiculum Hill",
        city: "Rome",
        location: { latitude: 41.8899, longitude: 12.4645 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A179",
        name: "Vittorio Emanuele II Monument",
        city: "Rome",
        location: { latitude: 41.8946, longitude: 12.4836 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A180",
        name: "Galleria Doria Pamphilj",
        city: "Rome",
        location: { latitude: 41.8966, longitude: 12.4815 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
    ],
  },
  {
    name: "Florence",
    location: {
      latitude: 43.7696,
      longitude: 11.2558,
    },
    image:
      "https://images.unsplash.com/photo-1592236717426-564f3e486d5b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A181",
        name: "Duomo di Firenze (Cattedrale di Santa Maria del Fiore)",
        city: "Florence",
        location: { latitude: 43.7735, longitude: 11.2559 },
        estimatedTime: 160,
        perPersonCost: 20,
      },
      {
        id: "A182",
        name: "Uffizi Gallery",
        city: "Florence",
        location: { latitude: 43.7677, longitude: 11.2558 },
        estimatedTime: 200,
        perPersonCost: 20,
      },
      {
        id: "A183",
        name: "Ponte Vecchio",
        city: "Florence",
        location: { latitude: 43.7679, longitude: 11.2531 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A184",
        name: "Galleria dell'Accademia",
        city: "Florence",
        location: { latitude: 43.7784, longitude: 11.2584 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A185",
        name: "Palazzo Vecchio",
        city: "Florence",
        location: { latitude: 43.7692, longitude: 11.2561 },
        estimatedTime: 100,
        perPersonCost: 20,
      },
      {
        id: "A186",
        name: "Campanile di Giotto",
        city: "Florence",
        location: { latitude: 43.7730, longitude: 11.2550 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A187",
        name: "Boboli Gardens",
        city: "Florence",
        location: { latitude: 43.7629, longitude: 11.2486 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A188",
        name: "Piazza della Signoria",
        city: "Florence",
        location: { latitude: 43.7697, longitude: 11.2556 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A189",
        name: "Bargello National Museum",
        city: "Florence",
        location: { latitude: 43.7687, longitude: 11.2591 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A190",
        name: "San Lorenzo Market",
        city: "Florence",
        location: { latitude: 43.777, longitude: 11.2525 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A191",
        name: "San Miniato al Monte",
        city: "Florence",
        location: { latitude: 43.7622, longitude: 11.265 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A192",
        name: "Piazzale Michelangelo",
        city: "Florence",
        location: { latitude: 43.7623, longitude: 11.2652 },
        estimatedTime: 80,
        perPersonCost: 0,
      },
      {
        id: "A193",
        name: "Loggia dei Lanzi",
        city: "Florence",
        location: { latitude: 43.7696, longitude: 11.2558 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A194",
        name: "Palazzo Pitti",
        city: "Florence",
        location: { latitude: 43.7677, longitude: 11.2494 },
        estimatedTime: 130,
        perPersonCost: 20,
      },
      {
        id: "A195",
        name: "Santa Maria Novella",
        city: "Florence",
        location: { latitude: 43.7748, longitude: 11.253 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A196",
        name: "Museo Galileo",
        city: "Florence",
        location: { latitude: 43.76773, longitude: 11.2549 },
        estimatedTime: 100,
        perPersonCost: 20,
      },
      {
        id: "A197",
        name: "Brancacci Chapel",
        city: "Florence",
        location: { latitude: 43.7675, longitude: 11.2496 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A198",
        name: "San Marco Museum",
        city: "Florence",
        location: { latitude: 43.7774, longitude: 11.2619 },
        estimatedTime: 80,
        perPersonCost: 20,
      },
      {
        id: "A199",
        name: "Strozzi Palace",
        city: "Florence",
        location: { latitude: 43.7712, longitude: 11.2517 },
        estimatedTime: 100,
        perPersonCost: 0,
      },
      {
        id: "A200",
        name: "Leonardo da Vinci Museum",
        city: "Florence",
        location: { latitude: 43.7739, longitude: 11.2569 },
        estimatedTime: 90,
        perPersonCost: 15,
      },
      {
        id: "A201",
        name: "Florence Baptistery",
        city: "Florence",
        location: { latitude: 43.7737, longitude: 11.2568 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A202",
        name: "Dante's House Museum",
        city: "Florence",
        location: { latitude: 43.771, longitude: 11.2569 },
        estimatedTime: 100,
        perPersonCost: 10,
      },
      {
        id: "A203",
        name: "Orsanmichele",
        city: "Florence",
        location: { latitude: 43.7722, longitude: 11.2559 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A204",
        name: "Medici Chapel",
        city: "Florence",
        location: { latitude: 43.7737, longitude: 11.2535 },
        estimatedTime: 100,
        perPersonCost: 20,
      },
      {
        id: "A205",
        name: "Museum of San Salvi",
        city: "Florence",
        location: { latitude: 43.7716, longitude: 11.2857 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A206",
        name: "Florence Charterhouse (Certosa di Firenze)",
        city: "Florence",
        location: { latitude: 43.7308, longitude: 11.2218 },
        estimatedTime: 170,
        perPersonCost: 20,
      },
      {
        id: "A207",
        name: "Vasari Corridor",
        city: "Florence",
        location: { latitude: 43.767, longitude: 11.2639 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A208",
        name: "Santa Croce Basilica",
        city: "Florence",
        location: { latitude: 43.7684, longitude: 11.2624 },
        estimatedTime: 100,
        perPersonCost: 0,
      },
      {
        id: "A209",
        name: "Pitti Palace Modern Art Gallery",
        city: "Florence",
        location: { latitude: 43.7678, longitude: 11.2498 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A210",
        name: "National Archaeological Museum of Florence",
        city: "Florence",
        location: { latitude: 43.7797, longitude: 11.2614 },
        estimatedTime: 100,
        perPersonCost: 20,
      },
    ],
  },
  {
    name: "San Francisco",
    location: {
      latitude: 37.7749,
      longitude: -122.4194,
    },
    image:
      "https://images.unsplash.com/photo-1500111709600-7761aa8216c7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A211",
        name: "Golden Gate Bridge",
        city: "San Francisco",
        location: { latitude: 37.8199, longitude: -122.4783 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A212",
        name: "Alcatraz Island",
        city: "San Francisco",
        location: { latitude: 37.8267, longitude: -122.4233 },
        estimatedTime: 180,
        perPersonCost: 20,
      },
      {
        id: "A213",
        name: "Fisherman's Wharf",
        city: "San Francisco",
        location: { latitude: 37.8097, longitude: -122.4166 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A214",
        name: "Lombard Street",
        city: "San Francisco",
        location: { latitude: 37.8021, longitude: -122.4187 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A215",
        name: "Golden Gate Park",
        city: "San Francisco",
        location: { latitude: 37.7694, longitude: -122.4862 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A216",
        name: "Pier 39",
        city: "San Francisco",
        location: { latitude: 37.8087, longitude: -122.4098 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A217",
        name: "Chinatown",
        city: "San Francisco",
        location: { latitude: 37.7941, longitude: -122.4078 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A218",
        name: "Coit Tower",
        city: "San Francisco",
        location: { latitude: 37.8024, longitude: -122.4058 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A219",
        name: "Palace of Fine Arts",
        city: "San Francisco",
        location: { latitude: 37.8029, longitude: -122.4487 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A220",
        name: "California Academy of Sciences",
        city: "San Francisco",
        location: { latitude: 37.7699, longitude: -122.4662 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A221",
        name: "San Francisco Museum of Modern Art",
        city: "San Francisco",
        location: { latitude: 37.7857, longitude: -122.4011 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A222",
        name: "Exploratorium",
        city: "San Francisco",
        location: { latitude: 37.801, longitude: -122.397 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A223",
        name: "Muir Woods National Monument",
        city: "San Francisco",
        location: { latitude: 37.8916, longitude: -122.5774 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A224",
        name: "San Francisco Botanical Garden",
        city: "San Francisco",
        location: { latitude: 37.7665, longitude: -122.4674 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A225",
        name: "Twin Peaks",
        city: "San Francisco",
        location: { latitude: 37.7544, longitude: -122.4477 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A226",
        name: "Asian Art Museum",
        city: "San Francisco",
        location: { latitude: 37.7807, longitude: -122.416 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A227",
        name: "De Young Museum",
        city: "San Francisco",
        location: { latitude: 37.7711, longitude: -122.4686 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A228",
        name: "Angel Island State Park",
        city: "San Francisco",
        location: { latitude: 37.8645, longitude: -122.4354 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A229",
        name: "Sutro Baths",
        city: "San Francisco",
        location: { latitude: 37.78, longitude: -122.5139 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A230",
        name: "Lands End",
        city: "San Francisco",
        location: { latitude: 37.7834, longitude: -122.5118 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A231",
        name: "San Francisco Cable Cars",
        city: "San Francisco",
        location: { latitude: 37.804, longitude: -122.4176 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A232",
        name: "Fort Point National Historic Site",
        city: "San Francisco",
        location: { latitude: 37.8102, longitude: -122.4765 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A233",
        name: "San Francisco Zoo",
        city: "San Francisco",
        location: { latitude: 37.732, longitude: -122.503 },
        estimatedTime: 90,
        perPersonCost: 30,
      },
      {
        id: "A234",
        name: "Contemporary Jewish Museum",
        city: "San Francisco",
        location: { latitude: 37.7858, longitude: -122.4031 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A235",
        name: "Walt Disney Family Museum",
        city: "San Francisco",
        location: { latitude: 37.8013, longitude: -122.4584 },
        estimatedTime: 60,
        perPersonCost: 50,
      },
      {
        id: "A236",
        name: "Japanese Tea Garden",
        city: "San Francisco",
        location: { latitude: 37.7701, longitude: -122.4707 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A237",
        name: "Randall Museum",
        city: "San Francisco",
        location: { latitude: 37.7649, longitude: -122.4389 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A238",
        name: "Museum of the African Diaspora",
        city: "San Francisco",
        location: { latitude: 37.7864, longitude: -122.4019 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A239",
        name: "Conservatory of Flowers",
        city: "San Francisco",
        location: { latitude: 37.7727, longitude: -122.4615 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A240",
        name: "San Francisco Maritime National Historical Park",
        city: "San Francisco",
        location: { latitude: 37.8058, longitude: -122.4314 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
    ],
  },
  {
    name: "Amsterdam",
    location: {
      latitude: 52.3667,
      longitude: 4.8945,
    },
    image:
      "https://images.unsplash.com/photo-1459679749680-18eb1eb37418?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A241",
        name: "Saint Nicholas Basilica",
        city: "Amsterdam",
        location: { latitude: 52.3783, longitude: 4.8975 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A242",
        name: "Museo Anne Frank",
        city: "Amsterdam",
        location: { latitude: 52.3752, longitude: 4.8835 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A243",
        name: "Rijksmuseum",
        city: "Amsterdam",
        location: { latitude: 52.3599, longitude: 4.8852 },
        estimatedTime: 180,
        perPersonCost: 10,
      },
      {
        id: "A244",
        name: "Canal Cruise",
        city: "Amsterdam",
        location: { latitude: 52.3676, longitude: 4.9041 },
        estimatedTime: 90,
        perPersonCost: 40,
      },
      {
        id: "A245",
        name: "Dam Square",
        city: "Amsterdam",
        location: { latitude: 52.3731, longitude: 4.8924 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A246",
        name: "Museumplein",
        city: "Amsterdam",
        location: { latitude: 52.3584, longitude: 4.8796 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A247",
        name: "Vondelpark",
        city: "Amsterdam",
        location: { latitude: 52.3587, longitude: 4.8683 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A248",
        name: "Heineken Experience",
        city: "Amsterdam",
        location: { latitude: 52.3578, longitude: 4.8914 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A249",
        name: "Red Light District",
        city: "Amsterdam",
        location: { latitude: 52.3721, longitude: 4.8966 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A250",
        name: "Zaanse Schans",
        city: "Amsterdam",
        location: { latitude: 52.4736, longitude: 4.8207 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A251",
        name: "Begijnhof",
        city: "Amsterdam",
        location: { latitude: 52.366, longitude: 4.8893 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A252",
        name: "NEMO Science Museum",
        city: "Amsterdam",
        location: { latitude: 52.3675, longitude: 4.9123 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A253",
        name: "Amsterdam Museum",
        city: "Amsterdam",
        location: { latitude: 52.3685, longitude: 4.8906 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A254",
        name: "Rembrandt House Museum",
        city: "Amsterdam",
        location: { latitude: 52.3696, longitude: 4.9011 },
        estimatedTime: 90,
        perPersonCost: 10,
      },
      {
        id: "A255",
        name: "Hermitage Amsterdam",
        city: "Amsterdam",
        location: { latitude: 52.3669, longitude: 4.9037 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A256",
        name: "Amsterdam Royal Palace",
        city: "Amsterdam",
        location: { latitude: 52.3732, longitude: 4.891 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A257",
        name: "Jordaan District",
        city: "Amsterdam",
        location: { latitude: 52.3738, longitude: 4.8806 },
        estimatedTime: 90,
        perPersonCost: 0,
      },
      {
        id: "A258",
        name: "Artis Royal Zoo",
        city: "Amsterdam",
        location: { latitude: 52.3661, longitude: 4.9138 },
        estimatedTime: 120,
        perPersonCost: 30,
      },
      {
        id: "A259",
        name: "Van Gogh Museum",
        city: "Amsterdam",
        location: { latitude: 52.3584, longitude: 4.881 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A260",
        name: "Stedelijk Museum Amsterdam",
        city: "Amsterdam",
        location: { latitude: 52.358, longitude: 4.8796 },
        estimatedTime: 90,
        perPersonCost: 20,
      },
      {
        id: "A261",
        name: "Nieuwe Kerk",
        city: "Amsterdam",
        location: { latitude: 52.374, longitude: 4.8918 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A262",
        name: "Amsterdam Tulip Museum",
        city: "Amsterdam",
        location: { latitude: 52.3676, longitude: 4.8908 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A263",
        name: "Rijksmuseum Gardens",
        city: "Amsterdam",
        location: { latitude: 52.3599, longitude: 4.8852 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A264",
        name: "De Wallen",
        city: "Amsterdam",
        location: { latitude: 52.3725, longitude: 4.8963 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A265",
        name: "Westergasfabriek",
        city: "Amsterdam",
        location: { latitude: 52.3864, longitude: 4.8693 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A266",
        name: "Albert Cuyp Market",
        city: "Amsterdam",
        location: { latitude: 52.3549, longitude: 4.8943 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A267",
        name: "Moco Museum",
        city: "Amsterdam",
        location: { latitude: 52.3583, longitude: 4.882 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A268",
        name: "Foam Photography Museum",
        city: "Amsterdam",
        location: { latitude: 52.3625, longitude: 4.8834 },
        estimatedTime: 60,
        perPersonCost: 20,
      },
      {
        id: "A269",
        name: "Amstelpark",
        city: "Amsterdam",
        location: { latitude: 52.3316, longitude: 4.8915 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
      {
        id: "A270",
        name: "Oude Kerk",
        city: "Amsterdam",
        location: { latitude: 52.3749, longitude: 4.8981 },
        estimatedTime: 60,
        perPersonCost: 0,
      },
    ],
  },
  {
    name: "Prague",
    location: {
      latitude: 50.0755,
      longitude: 14.4378,
    },
    image:
      "https://images.unsplash.com/photo-1564511287568-54483b52a35e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    attractions: [
      {
        id: "A271",
        name: "Charles Bridge",
        city: "Prague",
        location: { latitude: 50.0865, longitude: 14.4119 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A272",
        name: "Prague Castle",
        city: "Prague",
        location: { latitude: 50.091, longitude: 14.3996 },
        estimatedTime: 170,
        perPersonCost: 20,
      },
      {
        id: "A273",
        name: "Old Town Square",
        city: "Prague",
        location: { latitude: 50.087, longitude: 14.4204 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A274",
        name: "Astronomical Clock (Orloj)",
        city: "Prague",
        location: { latitude: 50.0875, longitude: 14.4215 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A275",
        name: "Republic Square",
        city: "Prague",
        location: { latitude: 50.087, longitude: 14.4284 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A276",
        name: "St. Vitus Cathedral",
        city: "Prague",
        location: { latitude: 50.0909, longitude: 14.3995 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A277",
        name: "Wenceslas Square",
        city: "Prague",
        location: { latitude: 50.0812, longitude: 14.4279 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A278",
        name: "Prague National Theatre",
        city: "Prague",
        location: { latitude: 50.0813, longitude: 14.4143 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A279",
        name: "Petrin Hill and Observation Tower",
        city: "Prague",
        location: { latitude: 50.0833, longitude: 14.4046 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A280",
        name: "Vysehrad",
        city: "Prague",
        location: { latitude: 50.0646, longitude: 14.4208 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A281",
        name: "Lennon Wall",
        city: "Prague",
        location: { latitude: 50.0862, longitude: 14.4084 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A282",
        name: "Kampa Island",
        city: "Prague",
        location: { latitude: 50.0842, longitude: 14.4093 },
        estimatedTime: 130,
        perPersonCost: 0,
      },
      {
        id: "A283",
        name: "Dancing House",
        city: "Prague",
        location: { latitude: 50.0755, longitude: 14.4144 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A284",
        name: "National Museum, Prague",
        city: "Prague",
        location: { latitude: 50.0755, longitude: 14.4378 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A285",
        name: "Strahov Monastery",
        city: "Prague",
        location: { latitude: 50.0851, longitude: 14.3915 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A286",
        name: "Clementinum",
        city: "Prague",
        location: { latitude: 50.0863, longitude: 14.4185 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A287",
        name: "John Lennon Statue",
        city: "Prague",
        location: { latitude: 50.0863, longitude: 14.4119 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A288",
        name: "Kinsky Palace",
        city: "Prague",
        location: { latitude: 50.0884, longitude: 14.4056 },
        estimatedTime: 120,
        perPersonCost: 30,
      },
      {
        id: "A289",
        name: "Prague Zoo",
        city: "Prague",
        location: { latitude: 50.117, longitude: 14.413 },
        estimatedTime: 220,
        perPersonCost: 20,
      },
      {
        id: "A290",
        name: "Spanish Synagogue",
        city: "Prague",
        location: { latitude: 50.0905, longitude: 14.419 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A291",
        name: "National Gallery in Prague",
        city: "Prague",
        location: { latitude: 50.0885, longitude: 14.4115 },
        estimatedTime: 150,
        perPersonCost: 20,
      },
      {
        id: "A292",
        name: "Prague Municipal House",
        city: "Prague",
        location: { latitude: 50.0874, longitude: 14.4257 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A293",
        name: "Strahov Library",
        city: "Prague",
        location: { latitude: 50.085, longitude: 14.3932 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A294",
        name: "Waldstein Palace",
        city: "Prague",
        location: { latitude: 50.0885, longitude: 14.4081 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A295",
        name: "Vysehrad Cemetery",
        city: "Prague",
        location: { latitude: 50.0634, longitude: 14.4178 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A296",
        name: "Naprstek Museum",
        city: "Prague",
        location: { latitude: 50.0849, longitude: 14.4209 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A297",
        name: "Emmaus Monastery",
        city: "Prague",
        location: { latitude: 50.0644, longitude: 14.4045 },
        estimatedTime: 120,
        perPersonCost: 20,
      },
      {
        id: "A298",
        name: "Petřín Gardens",
        city: "Prague",
        location: { latitude: 50.0833, longitude: 14.4021 },
        estimatedTime: 120,
        perPersonCost: 0,
      },
      {
        id: "A299",
        name: "Vysehrad Fortress",
        city: "Prague",
        location: { latitude: 50.0642, longitude: 14.4194 },
        estimatedTime: 150,
        perPersonCost: 0,
      },
      {
        id: "A300",
        name: "Museum Kampa",
        city: "Prague",
        location: { latitude: 50.0848, longitude: 14.4073 },
        estimatedTime: 130,
        perPersonCost: 20,
      },
    ],
  },
];

export default cities;
